apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "908990"
  annotations:
    github.com/project-slug: ibrt2016/terraform-azure-web-mybob555 # Change the value to your github repo which contains terraform code.
    backstage.io/techdocs-ref: dir:.
  links:
  - url: https://github.com/claranet/terraform-azurerm-vnet
    title: 'VNet Terraform Module'
    icon: github
  tags:
    - azure
    - vnet
    - terraform
    - existing-deployment
    - ticket-number-908990
    - stack-mybob555
    - env-dev
    - created-on-2024-07-28
  title: 'Addtional Azure Virtual Network - Ticket #908990' # you can give any title
  description: |
    Create additional **Azure Virtual Network** in stack **mybob555** and in **dev** environment\
    \
    **Ticket number:**  908990\
    **Created on:**  2024-07-28\
    **Details:**  Create additional **Azure Virtual network** in an existing **Resource Group**, in an existing stack **mybob555**, in **dev** environment and in **can-central** region\
    **Action:**  Create an additional **Virtual Network** in an existing **Resouce Group**\
    **Brand new deployment:**  No\
    **Azure region:**  can-central
    **Virtal network address space:**  10.11.0.0/16\
    **Virtal network suffix:**  001\
    **Stack name:**  mybob555\
    **Azure subscription:**  web
spec:
  type: service
  owner: user:guest
  lifecycle: experimental